# Generated by Django 2.2.6 on 2019-10-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True, verbose_name='URL')),
                ('interval', models.IntegerField(choices=[(30, '30 seconds'), (60, '60 seconds')], verbose_name='Refresh interval in seconds')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
