# Generated by Django 2.2.6 on 2019-10-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmonitor',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
